// App.jsx
import React, { useState, useMemo, useEffect } from 'react';
import { LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer, PieChart, Pie, Cell } from 'recharts';
import { Shield, AlertTriangle, Smile, Calendar, Search, Award, CheckCircle, ListFilter, Cpu, MessageSquare } from 'lucide-react';

// Import the data payload generated by Python VADER pipeline
import dashboardData from './dashboard_analytics.json';

export default function App() {
  // Core Operational State Managers
  const [searchTerm, setSearchTerm] = useState('');
  const [activeFilter, setActiveFilter] = useState('all');
  const [rowLimit, setRowLimit] = useState(10);
  
  // Real-time Text Sandbox Simulator States
  const [customInputText, setCustomInputText] = useState('');
  const [simulatedMetrics, setSimulatedMetrics] = useState(null);

  // 1. DATA AGGREGATION PIPELINE (Core Mathematical Metric Framework)
  const metrics = useMemo(() => {
    const total = dashboardData.length;
    const hateSpeechCount = dashboardData.filter(d => d.label === 1).length;
    const safeCount = total - hateSpeechCount;
    
    let avgPos = 0, avgNeg = 0;
    dashboardData.forEach(d => {
      avgPos += d.positive;
      avgNeg += d.negative;
    });

    return {
      total,
      hateSpeechCount,
      safeCount,
      safetyIndex: ((safeCount / total) * 100).toFixed(1),
      avgPositiveIntensity: (avgPos / total).toFixed(2),
      avgNegativeIntensity: (avgNeg / total).toFixed(2)
    };
  }, []);

  // 2. LIVE TEXT ANALYSIS ENGINE: Upgraded to real-time effect trigger loop
  useEffect(() => {
    // If the string is completely empty or just whitespace, reset the layout state cleanly
    if (!customInputText.trim()) {
      setSimulatedMetrics(null);
      return;
    }

    const lowerText = customInputText.toLowerCase();
    
    // Comprehensive token validation matrices
    const toxicWords = ['hate', 'stupid', 'ugly', 'dumb', 'trash', 'racist', 'sexist', 'bad', 'worst', 'fuck', 'bitch', 'asshole', 'idiot', 'bullshit', 'motherfucker'];
    const positiveWords = ['love', 'great', 'happy', 'beautiful', 'friend', 'awesome', 'good', 'nice', 'excellent', 'amazing'];

    let negativeHits = 0;
    let positiveHits = 0;

    toxicWords.forEach(w => { if (lowerText.includes(w)) negativeHits += 1; });
    positiveWords.forEach(w => { if (lowerText.includes(w)) positiveHits += 1; });

    const negScore = negativeHits > 0 ? Math.min(0.4 + negativeHits * 0.2, 1.0) : 0.0;
    const posScore = positiveHits > 0 ? Math.min(0.2 + positiveHits * 0.2, 1.0) : 0.0;
    const compoundScore = posScore - negScore;
    const predictedLabel = negScore > 0.3 ? 1 : 0;

    setSimulatedMetrics({
      positive: posScore,
      negative: negScore,
      compound: compoundScore,
      label: predictedLabel
    });
  }, [customInputText]); // Triggers automatically on every single keystroke edit!

  // 3. CHART TRANSFORMATIONS
  const timelineChartData = useMemo(() => {
    return dashboardData.slice(0, 30).map(item => ({
      time: item.timestamp.split(' ')[1], 
      'Compound Sentiment': item.compound,
      'Positivity Index': item.positive,
      'Negativity Index': item.negative
    }));
  }, []);

  const pieChartData = [
    { name: 'Safe Discourse', value: metrics.safeCount, color: '#10B981' }, 
    { name: 'Flagged Content', value: metrics.hateSpeechCount, color: '#EF4444' } 
  ];

  // 4. DATA TABLE QUERY EXTRACTION FILTER
  const filteredTweets = useMemo(() => {
    const cleanFiltered = dashboardData.filter(item => {
      const matchesSearch = item.ultra_clean_tweet.toLowerCase().includes(searchTerm.toLowerCase());
      if (!matchesSearch) return false;

      if (activeFilter === 'safe') return item.label === 0;    
      if (activeFilter === 'flagged') return item.label === 1; 
      if (activeFilter === 'intense') return item.positive > 0.3 || item.negative > 0.3;

      return true; 
    });

    if (rowLimit === -1) return cleanFiltered;
    return cleanFiltered.slice(0, rowLimit);
  }, [searchTerm, activeFilter, rowLimit]);

  return (
    <div style={{ minHeight: '100vh', backgroundColor: '#0A0F1D', color: '#E2E8F0', fontFamily: 'system-ui, -apple-system, sans-serif', padding: '32px', boxSizing: 'border-box' }}>
      
      {/* PREMIUM MODERN BRANDING HEADER */}
      <header style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', background: 'linear-gradient(135deg, rgba(30, 41, 59, 0.4), rgba(15, 23, 42, 0.6))', padding: '24px 32px', borderRadius: '16px', border: '1px solid rgba(255, 255, 255, 0.05)', marginBottom: '32px', backdropFilter: 'blur(12px)', boxShadow: '0 4px 30px rgba(0, 0, 0, 0.2)' }}>
        <div>
          <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
            <div style={{ background: 'linear-gradient(135deg, #38BDF8, #0EA5E9)', padding: '10px', borderRadius: '12px', display: 'flex', alignItems: 'center', justifyContent: 'center', boxShadow: '0 0 20px rgba(56, 189, 248, 0.2)' }}>
              <Shield size={28} color="#0A0F1D" style={{ strokeWidth: 2.5 }} />
            </div>
            <div>
              <h1 style={{ fontSize: '24px', fontWeight: '800', letterSpacing: '-0.025em', margin: 0, background: 'linear-gradient(to right, #FFFFFF, #94A3B8)', WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent' }}>
                Sentinel Lync Engine
              </h1>
              <p style={{ color: '#64748B', fontSize: '13px', fontWeight: '500', marginTop: '2px', marginBottom: 0 }}>Advanced Platform Safety & Linguistic Sentiment Analytics Dashboard</p>
            </div>
          </div>
        </div>
        <div style={{ display: 'flex', alignItems: 'center', gap: '8px', backgroundColor: 'rgba(56, 189, 248, 0.06)', padding: '10px 18px', borderRadius: '10px', border: '1px solid rgba(56, 189, 248, 0.15)' }}>
          <Award size={18} color="#38BDF8" />
          <span style={{ fontSize: '13px', fontWeight: '600', color: '#38BDF8', letterSpacing: '0.05em', textTransform: 'uppercase' }}>PREMIUM ACCESS</span>
        </div>
      </header>

      {/* TOP ROW: PREMIUM GLASSMORPHIC CLICKABLE CARDS */}
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(240px, 1fr))', gap: '20px', marginBottom: '32px' }}>
        
        {/* CARD 1: TOTAL RECORDS */}
        <div onClick={() => { setActiveFilter('all'); setRowLimit(10); }}
          style={{ backgroundColor: 'rgba(30, 41, 59, 0.4)', padding: '24px', borderRadius: '16px', cursor: 'pointer', transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
            border: activeFilter === 'all' ? '1px solid #38BDF8' : '1px solid rgba(255, 255, 255, 0.05)',
            boxShadow: activeFilter === 'all' ? '0 0 25px rgba(56, 189, 248, 0.1)' : 'none', transform: activeFilter === 'all' ? 'translateY(-2px)' : 'translateY(0)' }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', color: '#38BDF8' }}>
            <span style={{ fontSize: '13px', fontWeight: '600', textTransform: 'uppercase', letterSpacing: '0.05em' }}>Total Corpus Stream</span>
            <Calendar size={18} />
          </div>
          <h2 style={{ fontSize: '36px', fontWeight: '800', margin: '14px 0 6px 0', letterSpacing: '-0.05em', color: '#FFFFFF' }}>{metrics.total}</h2>
          <span style={{ fontSize: '12px', color: activeFilter === 'all' ? '#38BDF8' : '#475569', fontWeight: '600' }}>
            {activeFilter === 'all' ? '● Active View Filter' : 'Click to map full array'}
          </span>
        </div>

        {/* CARD 2: SAFETY METRIC */}
        <div onClick={() => { setActiveFilter('safe'); setRowLimit(10); }}
          style={{ backgroundColor: 'rgba(30, 41, 59, 0.4)', padding: '24px', borderRadius: '16px', cursor: 'pointer', transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
            border: activeFilter === 'safe' ? '1px solid #10B981' : '1px solid rgba(255, 255, 255, 0.05)',
            boxShadow: activeFilter === 'safe' ? '0 0 25px rgba(16, 185, 129, 0.1)' : 'none', transform: activeFilter === 'safe' ? 'translateY(-2px)' : 'translateY(0)' }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', color: '#10B981' }}>
            <span style={{ fontSize: '13px', fontWeight: '600', textTransform: 'uppercase', letterSpacing: '0.05em' }}>Safety Dominance Index</span>
            <Smile size={18} />
          </div>
          <h2 style={{ fontSize: '36px', fontWeight: '800', margin: '14px 0 6px 0', letterSpacing: '-0.05em', color: '#FFFFFF' }}>{metrics.safetyIndex}%</h2>
          <span style={{ fontSize: '12px', color: activeFilter === 'safe' ? '#10B981' : '#475569', fontWeight: '600' }}>
            {activeFilter === 'safe' ? '● Active View Filter' : 'Click to isolate secure logs'}
          </span>
        </div>

        {/* CARD 3: HATE SPEECH SPECS */}
        <div onClick={() => { setActiveFilter('flagged'); setRowLimit(10); }}
          style={{ backgroundColor: 'rgba(30, 41, 59, 0.4)', padding: '24px', borderRadius: '16px', cursor: 'pointer', transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
            border: activeFilter === 'flagged' ? '1px solid #EF4444' : '1px solid rgba(255, 255, 255, 0.05)',
            boxShadow: activeFilter === 'flagged' ? '0 0 25px rgba(239, 68, 68, 0.1)' : 'none', transform: activeFilter === 'flagged' ? 'translateY(-2px)' : 'translateY(0)' }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', color: '#EF4444' }}>
            <span style={{ fontSize: '13px', fontWeight: '600', textTransform: 'uppercase', letterSpacing: '0.05em' }}>Flagged Infractions</span>
            <AlertTriangle size={18} />
          </div>
          <h2 style={{ fontSize: '36px', fontWeight: '800', margin: '14px 0 6px 0', letterSpacing: '-0.05em', color: '#FFFFFF' }}>{metrics.hateSpeechCount}</h2>
          <span style={{ fontSize: '12px', color: activeFilter === 'flagged' ? '#EF4444' : '#475569', fontWeight: '600' }}>
            {activeFilter === 'flagged' ? '● Active View Filter' : 'Click to audit anomalies'}
          </span>
        </div>

        {/* CARD 4: MEAN SCORING */}
        <div onClick={() => { setActiveFilter('intense'); setRowLimit(10); }}
          style={{ backgroundColor: 'rgba(30, 41, 59, 0.4)', padding: '24px', borderRadius: '16px', cursor: 'pointer', transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
            border: activeFilter === 'intense' ? '1px solid #A855F7' : '1px solid rgba(255, 255, 255, 0.05)',
            boxShadow: activeFilter === 'intense' ? '0 0 25px rgba(168, 85, 247, 0.1)' : 'none', transform: activeFilter === 'intense' ? 'translateY(-2px)' : 'translateY(0)' }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', color: '#A855F7' }}>
            <span style={{ fontSize: '13px', fontWeight: '600', textTransform: 'uppercase', letterSpacing: '0.05em' }}>Mean Lexical Density</span>
            <Cpu size={18} />
          </div>
          <h2 style={{ fontSize: '20px', fontWeight: '800', margin: '26px 0 6px 0', color: '#FFFFFF' }}>
            +{metrics.avgPositiveIntensity} <span style={{ color: '#475569', fontWeight: '300', fontSize: '14px' }}>|</span> -{metrics.avgNegativeIntensity}
          </h2>
          <span style={{ fontSize: '12px', color: activeFilter === 'intense' ? '#A855F7' : '#475569', fontWeight: '600' }}>
            {activeFilter === 'intense' ? '● Active View Filter' : 'Click to review distribution'}
          </span>
        </div>

      </div>

      {/* FIXED AND UPDATED TEXT SIMULATOR ENGINE (PIPELINE CARD REMOVED AS REQUESTED) */}
      <div style={{ width: '100%', marginBottom: '32px' }}>
        <div style={{ backgroundColor: 'rgba(30, 41, 59, 0.25)', padding: '28px', borderRadius: '20px', border: '1px solid rgba(255, 255, 255, 0.05)', background: 'linear-gradient(to bottom right, rgba(30, 41, 59, 0.3), rgba(15, 23, 42, 0.4))' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '10px', marginBottom: '6px' }}>
            <MessageSquare size={20} color="#38BDF8" />
            <h3 style={{ fontSize: '18px', fontWeight: '700', margin: 0, color: '#FFFFFF', letterSpacing: '-0.01em' }}>Real-Time Arbitrary Text Evaluation Engine Simulator</h3>
          </div>
          <p style={{ color: '#64748B', fontSize: '13px', marginTop: 0, marginBottom: '20px', fontWeight: '500' }}>Upgraded Kernel Execution Model: Type any raw string sequence below to execute live, sub-second lexical token classification mappings.</p>
          
          {/* CONTROL SECTION BUTTON BUG RESOLVED BY DROPPING FORM WRAPPERS */}
          <div style={{ position: 'relative', display: 'flex', alignItems: 'center', width: '100%', marginBottom: '24px' }}>
            <input 
              type="text"
              placeholder="Type testing text string here... (e.g., 'fuck', 'hate' or positive expressions to test responsive state shifts)"
              value={customInputText}
              onChange={(e) => setCustomInputText(e.target.value)}
              style={{ width: '100%', backgroundColor: '#090F1D', color: '#FFFFFF', border: '1px solid rgba(255, 255, 255, 0.08)', borderRadius: '12px', padding: '16px 20px', outline: 'none', fontSize: '14px', transition: 'all 0.2s', boxSizing: 'border-box' }}
            />
            {customInputText && (
              <button 
                onClick={() => setCustomInputText('')}
                style={{ position: 'absolute', right: '16px', backgroundColor: 'rgba(255, 255, 255, 0.05)', color: '#94A3B8', border: 'none', borderRadius: '6px', padding: '6px 12px', fontSize: '12px', cursor: 'pointer', fontWeight: '600' }}
              >
                Clear Input
              </button>
            )}
          </div>

          {/* DYNAMIC METRIC LAYOUT COMPONENT */}
          {simulatedMetrics ? (
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))', gap: '16px', backgroundColor: '#090F1D', padding: '20px', borderRadius: '14px', border: '1px solid rgba(255, 255, 255, 0.03)' }}>
              <div style={{ display: 'flex', flexDirection: 'column', gap: '4px' }}>
                <span style={{ color: '#475569', fontSize: '11px', fontWeight: '700', textTransform: 'uppercase', letterSpacing: '0.05em' }}>Model Classification</span>
                <span style={{ 
                  color: simulatedMetrics.label === 1 ? '#EF4444' : '#10B981',
                  fontSize: '14px', fontWeight: '700', display: 'flex', alignItems: 'center', gap: '6px'
                }}>
                  <div style={{ width: '8px', height: '8px', borderRadius: '50%', backgroundColor: simulatedMetrics.label === 1 ? '#EF4444' : '#10B981' }}></div>
                  {simulatedMetrics.label === 1 ? 'Flagged Violation' : 'Secure Discourse'}
                </span>
              </div>
              <div style={{ display: 'flex', flexDirection: 'column', gap: '4px' }}>
                <span style={{ color: '#475569', fontSize: '11px', fontWeight: '700', textTransform: 'uppercase', letterSpacing: '0.05em' }}>Positivity Metric</span>
                <span style={{ color: '#10B981', fontSize: '15px', fontWeight: '700' }}>{simulatedMetrics.positive.toFixed(2)}</span>
              </div>
              <div style={{ display: 'flex', flexDirection: 'column', gap: '4px' }}>
                <span style={{ color: '#475569', fontSize: '11px', fontWeight: '700', textTransform: 'uppercase', letterSpacing: '0.05em' }}>Negativity Metric</span>
                <span style={{ color: '#EF4444', fontSize: '15px', fontWeight: '700' }}>{simulatedMetrics.negative.toFixed(2)}</span>
              </div>
              <div style={{ display: 'flex', flexDirection: 'column', gap: '4px' }}>
                <span style={{ color: '#475569', fontSize: '11px', fontWeight: '700', textTransform: 'uppercase', letterSpacing: '0.05em' }}>Compound Index Amplitude</span>
                <span style={{ color: '#38BDF8', fontSize: '15px', fontWeight: '700' }}>{simulatedMetrics.compound.toFixed(2)}</span>
              </div>
            </div>
          ) : (
            <div style={{ textAlign: 'center', padding: '16px', color: '#475569', fontSize: '13px', fontStyle: 'italic', border: '1px dashed rgba(255, 255, 255, 0.03)', borderRadius: '12px' }}>
              Waiting for live keystroke inputs... Character array sequence empty.
            </div>
          )}
        </div>
      </div>

      {/* MIDDLE SECTION: CHARTING ENGINE MAPS */}
      <div style={{ display: 'grid', gridTemplateColumns: '2fr 1fr', gap: '24px', marginBottom: '32px' }}>
        
        {/* LINE DATA COMPONENT */}
        <div style={{ backgroundColor: 'rgba(30, 41, 59, 0.25)', padding: '24px', borderRadius: '20px', border: '1px solid rgba(255, 255, 255, 0.05)' }}>
          <h3 style={{ fontSize: '16px', fontWeight: '700', margin: '0 0 20px 0', color: '#FFFFFF', letterSpacing: '-0.01em' }}>Chronological Sentiment Oscillations</h3>
          <div style={{ width: '100%', height: '260px' }}>
            <ResponsiveContainer>
              <LineChart data={timelineChartData}>
                <CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,0.03)" />
                <XAxis dataKey="time" stroke="#475569" fontSize={11} tickLine={false} />
                <YAxis stroke="#475569" fontSize={11} domain={[-1, 1]} tickLine={false} axisLine={false} />
                <Tooltip contentStyle={{ backgroundColor: '#0F172A', borderColor: 'rgba(255,255,255,0.08)', color: '#F8FAFC', borderRadius: '10px' }} />
                <Legend wrapperStyle={{ fontSize: '12px', paddingTop: '10px' }} />
                <Line type="monotone" dataKey="Compound Sentiment" stroke="#38BDF8" strokeWidth={2.5} dot={{ r: 1.5, fill: '#38BDF8' }} activeDot={{ r: 4 }} />
                <Line type="monotone" dataKey="Positivity Index" stroke="#10B981" strokeWidth={1.2} strokeDasharray="5 5" dot={false} />
                <Line type="monotone" dataKey="Negativity Index" stroke="#EF4444" strokeWidth={1.2} strokeDasharray="5 5" dot={false} />
              </LineChart>
            </ResponsiveContainer>
          </div>
        </div>

        {/* PIE LAYOUT CHART */}
        <div style={{ backgroundColor: 'rgba(30, 41, 59, 0.25)', padding: '24px', borderRadius: '20px', border: '1px solid rgba(255, 255, 255, 0.05)', display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center' }}>
          <h3 style={{ fontSize: '16px', fontWeight: '700', margin: '0 0 16px 0', color: '#FFFFFF', width: '100%', textAlign: 'left', letterSpacing: '-0.01em' }}>Class Proportions</h3>
          <div style={{ width: '100%', height: '180px' }}>
            <ResponsiveContainer>
              <PieChart>
                <Pie data={pieChartData} cx="50%" cy="50%" innerRadius={52} outerRadius={72} paddingAngle={4} dataKey="value">
                  {pieChartData.map((entry, index) => (
                    <Cell key={`cell-${index}`} fill={entry.color} />
                  ))}
                </Pie>
                <Tooltip contentStyle={{ backgroundColor: '#0F172A', borderColor: 'rgba(255,255,255,0.08)', color: '#F8FAFC' }} />
              </PieChart>
            </ResponsiveContainer>
          </div>
          <div style={{ display: 'flex', flexDirection: 'column', gap: '8px', width: '100%', marginTop: '12px' }}>
            {pieChartData.map((item, idx) => (
              <div key={idx} style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', fontSize: '12px', fontWeight: '500' }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                  <div style={{ width: '8px', height: '8px', borderRadius: '50%', backgroundColor: item.color }}></div>
                  <span style={{ color: '#94A3B8' }}>{item.name}</span>
                </div>
                <strong style={{ color: '#FFFFFF' }}>{item.value.toLocaleString()} rows</strong>
              </div>
            ))}
          </div>
        </div>

      </div>

      {/* BOTTOM ROW: ADVANCED FILTERABLE DATA STREAM LAYOUT */}
      <div style={{ backgroundColor: 'rgba(30, 41, 59, 0.25)', padding: '24px', borderRadius: '20px', border: '1px solid rgba(255, 255, 255, 0.05)' }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '20px', flexWrap: 'wrap', gap: '16px' }}>
          <div>
            <h3 style={{ fontSize: '18px', fontWeight: '700', margin: 0, color: '#FFFFFF', letterSpacing: '-0.01em' }}>
              Data Stream Corpus Logs: <span style={{ color: '#38BDF8', textTransform: 'capitalize' }}>{activeFilter} View</span>
            </h3>
            <span style={{ fontSize: '12px', color: '#64748B', fontWeight: '500' }}>Isolating database allocation rows dynamically based on dashboard card filters.</span>
          </div>
          
          <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
            
            {/* PAGINATION FILTER ROW STEP SIZE */}
            <div style={{ display: 'flex', alignItems: 'center', gap: '6px', backgroundColor: '#090F1D', border: '1px solid rgba(255,255,255,0.05)', padding: '6px 12px', borderRadius: '8px' }}>
              <ListFilter size={14} color="#64748B" />
              <select 
                value={rowLimit} 
                onChange={(e) => setRowLimit(Number(e.target.value))}
                style={{ backgroundColor: 'transparent', color: '#94A3B8', border: 'none', outline: 'none', fontSize: '13px', cursor: 'pointer', fontWeight: '600' }}
              >
                <option value={10} style={{ backgroundColor: '#0A0F1D' }}>Show 10 Rows</option>
                <option value={100} style={{ backgroundColor: '#0A0F1D' }}>Show 100 Rows</option>
                <option value={1000} style={{ backgroundColor: '#0A0F1D' }}>Show 1000 Rows</option>
                <option value={10000} style={{ backgroundColor: '#0A0F1D' }}>Show 10000 Rows</option>
                <option value={-1} style={{ backgroundColor: '#0A0F1D' }}>Show ALL Data</option>
              </select>
            </div>

            {/* KEYWORD BAR SEARCH */}
            <div style={{ position: 'relative', display: 'flex', alignItems: 'center' }}>
              <Search size={16} style={{ position: 'absolute', left: '12px', color: '#475569' }} />
              <input 
                type="text" 
                placeholder="Search matching text..." 
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
                style={{ backgroundColor: '#090F1D', color: '#FFFFFF', border: '1px solid rgba(255,255,255,0.05)', borderRadius: '8px', padding: '8px 12px 8px 36px', width: '200px', fontSize: '13px', outline: 'none' }}
              />
            </div>
          </div>
        </div>

        {/* COMPONENT TABLE GRID VIEW WITH FIXED HEADERS SCROLL BOUNDS */}
        <div style={{ overflowX: 'auto', maxHeight: '400px', overflowY: 'auto', borderRadius: '12px', border: '1px solid rgba(255, 255, 255, 0.03)' }}>
          {filteredTweets.length === 0 ? (
            <p style={{ textAlign: 'center', color: '#475569', padding: '32px', fontStyle: 'italic', margin: 0 }}>No historical data rows match your current logical filter strings.</p>
          ) : (
            <table style={{ width: '100%', borderCollapse: 'collapse', textAlign: 'left', fontSize: '13px' }}>
              <thead style={{ position: 'sticky', top: 0, backgroundColor: '#111827', zIndex: 10, borderBottom: '1px solid rgba(255,255,255,0.05)' }}>
                <tr style={{ color: '#64748B', fontWeight: '600' }}>
                  <th style={{ padding: '14px 16px' }}>Vector ID</th>
                  <th style={{ padding: '14px 16px' }}>Chronology</th>
                  <th style={{ padding: '14px 16px' }}>Purified Tokenized Tweet Sequence</th>
                  <th style={{ padding: '14px 16px' }}>Compound Score</th>
                  <th style={{ padding: '14px 16px' }}>Classification Status</th>
                </tr>
              </thead>
              <tbody>
                {filteredTweets.map((tweet) => (
                  <tr key={tweet.id} style={{ borderBottom: '1px solid rgba(255,255,255,0.02)', backgroundColor: tweet.label === 1 ? 'rgba(239, 68, 68, 0.02)' : 'transparent', transition: 'background-color 0.2s' }}>
                    <td style={{ padding: '14px 16px', fontWeight: '600', color: '#475569' }}>#{tweet.id}</td>
                    <td style={{ padding: '14px 16px', color: '#64748B' }}>{tweet.timestamp}</td>
                    <td style={{ padding: '14px 16px', fontStyle: 'italic', color: '#94A3B8', maxWidth: '400px', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>"{tweet.ultra_clean_tweet}"</td>
                    <td style={{ padding: '14px 16px', fontWeight: '700', color: tweet.compound >= 0 ? '#10B981' : '#EF4444' }}>
                      {tweet.compound > 0 ? `+${tweet.compound.toFixed(2)}` : tweet.compound.toFixed(2)}
                    </td>
                    <td style={{ padding: '14px 16px' }}>
                      <span style={{ 
                        backgroundColor: tweet.label === 1 ? 'rgba(239, 68, 68, 0.1)' : 'rgba(16, 185, 129, 0.1)', 
                        color: tweet.label === 1 ? '#EF4444' : '#10B981', 
                        padding: '4px 10px', borderRadius: '6px', fontSize: '11px', fontWeight: '700', letterSpacing: '0.02em'
                      }}>
                        {tweet.label === 1 ? 'Hate Speech Violator' : 'Verified Secure'}
                      </span>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          )}
        </div>
      </div>

    </div>
  );
}